### ISSUE TITLE
postgresql-client output?

### ISSUE THREAD

**Issue by maresb** [conda-forge/postgresql-feedstock#95]
Would there be interest/support for adding an output for just the client binaries like `psql`, `pg_dump` and `pg_restore`? I'd personally find this extremely useful.

I'd like to duplicate the functionality of [the `postgresql-client` Ubuntu package](http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-12/postgresql-client-12_12.7-1.pgdg20.04%2B1_amd64.deb). (Note that [the `postgresql` Ubuntu package](http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-12/postgresql-12_12.7-1.pgdg20.04%2B1_amd64.deb) depends on `postgresql-client`.)

For reference, some details of this Debian package are as follows:

The Debian control file is:
```yaml
Package: postgresql-client-12
Source: postgresql-12
Version: 12.7-1.pgdg20.04+1
Architecture: amd64
Maintainer: Debian PostgreSQL Maintainers <team+postgresql@tracker.debian.org>
Installed-Size: 6087
Depends: libpq5 (>= 12.7), postgresql-client-common (>= 182~), sensible-utils, libc6 (>= 2.17), libedit2 (>= 3.1-20180525-0), zlib1g (>= 1:1.1.4)
Suggests: postgresql-12, postgresql-doc-12
Conflicts: postgresql-server-dev-12 (<< 12.1-2~)
Replaces: postgresql-server-dev-12 (<< 12.1-2~)
Provides: postgresql-client
Section: database
Priority: optional
Multi-Arch: foreign
Homepage: http://www.postgresql.org/
Description: front-end programs for PostgreSQL 12
 This package contains client and administrative programs for
 PostgreSQL: these are the interactive terminal client psql and
 programs for creating and removing users and databases.
 .
 This is the client package for PostgreSQL 12. If you install
 PostgreSQL 12 on a standalone machine, you need the server package
 postgresql-12, too. On a network, you can install this package on
 many client machines, while the server package may be installed on
 only one machine.
 .
 PostgreSQL is an object-relational SQL database management system.
```

and the subset of files which are installed to `usr/lib/postgresql/12/ `, is:
```
  usr/lib/postgresql/12/bin/clusterdb
  usr/lib/postgresql/12/bin/createdb
  usr/lib/postgresql/12/bin/createuser
  usr/lib/postgresql/12/bin/dropdb
  usr/lib/postgresql/12/bin/dropuser
  usr/lib/postgresql/12/bin/pg_basebackup
  usr/lib/postgresql/12/bin/pg_config
  usr/lib/postgresql/12/bin/pg_dump
  usr/lib/postgresql/12/bin/pg_dumpall
  usr/lib/postgresql/12/bin/pg_isready
  usr/lib/postgresql/12/bin/pg_receivewal
  usr/lib/postgresql/12/bin/pg_recvlogical
  usr/lib/postgresql/12/bin/pg_restore
  usr/lib/postgresql/12/bin/psql
  usr/lib/postgresql/12/bin/reindexdb
  usr/lib/postgresql/12/bin/vacuumdb
  usr/lib/postgresql/12/lib/pgxs/config/install-sh
  usr/lib/postgresql/12/lib/pgxs/config/missing
  usr/lib/postgresql/12/lib/pgxs/src/Makefile.global
  usr/lib/postgresql/12/lib/pgxs/src/Makefile.port
  usr/lib/postgresql/12/lib/pgxs/src/Makefile.shlib
  usr/lib/postgresql/12/lib/pgxs/src/makefiles/pgxs.mk
  usr/lib/postgresql/12/lib/pgxs/src/nls-global.mk
  usr/lib/postgresql/12/lib/pgxs/src/pl/plpython/regress-python3-mangle.mk
  usr/lib/postgresql/12/lib/pgxs/src/test/perl/PostgresNode.pm
  usr/lib/postgresql/12/lib/pgxs/src/test/perl/RecursiveCopy.pm
  usr/lib/postgresql/12/lib/pgxs/src/test/perl/SimpleTee.pm
  usr/lib/postgresql/12/lib/pgxs/src/test/perl/TestLib.pm
  usr/lib/postgresql/12/lib/pgxs/src/test/regress/pg_regress
```
